### ISSUE TITLE
Unable to use it with Java.

### ISSUE THREAD

**Issue by harshapulikollu** [armcha/DebugBanner#1]
I'm unable to use the dependency with Java code. Is this dependency works with Java or only with kotlin!
If it works with Java too, then please provide how to do it. Else provide an alternative or a work around for this. Thanks in advance.

**Comment by armcha** [comment]
I will add it later in the description

```java
public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        DebugBanner.Companion.init(this, new Banner());
    }
}
```
